In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df1=pd.read_csv('/content/drive/MyDrive/Copy of job_and_app_movement.csv')
df1.head()

,Unnamed: 0,job_id,posted_at,applicatoion movment craetion date,applicatoion movment updated date,company_id,Application ID,JS ID,Application State ID,Application State,Unlock Status,Application Score
0,0,9827,2018-01-04 17:33:33,2019-03-29 00:55:44,2019-03-29 00:55:44,f602420e,10989004,294f0a69,5,Shortlisted,Unlocked,81
1,1,64740,2018-01-01 12:04:17,2019-03-29 00:55:44,2019-03-29 00:55:44,589bda80,11046309,456b33e7,5,Shortlisted,Unlocked,64
2,2,39358,2018-01-02 01:02:46,2019-03-29 00:55:44,2019-03-29 00:55:44,47407780,11049478,923d398e,5,Shortlisted,Unlocked,67
3,3,55332,2018-01-02 11:02:55,2019-03-29 00:55:44,2019-03-29 00:55:44,179cae5c,11063512,fb59a72c,13,Rejected,Unlocked,75
4,4,76730,2018-01-01 13:50:29,2019-03-29 00:55:44,2019-03-29 00:55:44,db273518,11069229,a070b800,5,Shortlisted,Unlocked,86

In [4]:
df1.drop(columns=["Unnamed: 0","posted_at","applicatoion movment craetion date","applicatoion movment updated date","company_id","Application State ID","Unlock Status"],inplace=True)
df1.head(5)

   job_id  Application ID     JS ID Application State  Application Score
0    9827        10989004  294f0a69       Shortlisted                 81
1   64740        11046309  456b33e7       Shortlisted                 64
2   39358        11049478  923d398e       Shortlisted                 67
3   55332        11063512  fb59a72c          Rejected                 75
4   76730        11069229  a070b800       Shortlisted                 86

In [5]:
df1.rename(columns = {'JS ID':'js_id'}, inplace = True)
df1

         job_id  Application ID     js_id Application State  Application Score
0          9827        10989004  294f0a69       Shortlisted                 81
1         64740        11046309  456b33e7       Shortlisted                 64
2         39358        11049478  923d398e       Shortlisted                 67
3         55332        11063512  fb59a72c          Rejected                 75
4         76730        11069229  a070b800       Shortlisted                 86
...         ...             ...       ...               ...                ...
2979083   30931        26827877  77461b47          Rejected                 49
2979084   75954        26879343  b324a642          Rejected                 62
2979085   70435        26988602  fa162ca1          Rejected                 85
2979086   83565        27062059  b487cdf8          Rejected                 53
2979087   59885        27098010  ab2d7eff          Rejected                 36

[2979088 rows x 5 columns]

In [ ]:
# # Group the DataFrame by 'js_id' and calculate the mean of 'Application Score' for each 'js_id'.
# result_df = df1.groupby('js_id')['Application Score'].mean().reset_index()
# # Save the result to a new CSV file if needed.
# result_df.to_csv('unique_js_id_scores.csv', index=False)

In [9]:
data=pd.read_csv('/content/FinalTable (1).csv')

In [10]:
data

,js_id,Application Score,text_without_stopwords,job_titles,career_level,js_preference_work_role
0,0001c5fd,52.666667,productmarketing leadgeneration publicspeaking...,"account executive,Account Manager,Marketing Sp...",Experienced (Non-Manager),"Medical/Healthcare, Pharmaceutical, Marketing/..."
1,0003611b,67.500000,photography shopdrawings,"Marketing,Managing Director, Marketing,Managin...",Manager,"Pharmaceutical, Operations/Management, Educati..."
2,0006181b,48.000000,microsoftoffice adobephotoshop communicationdi...,"Customer service,Banking,Call Center Agent,Acc...",Entry Level,"Administration, Banking, Sales/Retail, Manufac..."
3,00068f53,63.600000,computerskills bookkeeping,"Accountant,financial analyst, Accountant,finan...",Entry Level,"Banking, Accounting/Finance"
4,00078680,62.000000,accounting bookkeepingaccountmanagement dataan...,"Senior Accountant,accountant, Senior Accountan...",Experienced (Non-Manager),"Banking, Accounting/Finance"
...,...,...,...,...,...,...
107229,fffcda9e,39.000000,computerskills communication,"medical insurance adviser,dentist",Entry Level,Medical/Healthcare
107230,fffcfbfd,62.500000,handskills fastlearnerworkanything,"Dentist,company,parttime,Dentistry,Dental Clin...",Experienced (Non-Manager),"Other, Medical/Healthcare, Human Resources, Ed..."
107231,fffdc731,52.666667,hardworker financialanalysis mathematicalskill...,"bank,Compliance Specialist,Internal Auditor,Ri...",Experienced (Non-Manager),"Strategy/Consulting, Accounting/Finance, Banking"
107232,fffe6209,37.111111,matlab microsoftoffice proteus arduino solidwo...,"COMMUNICATION ENGINEERING,ELECTEICAL ENGINEERI...",Entry Level,"Engineering - Mechanical/Electrical, Engineeri..."
107233,ffffbf23,42.000000,photography photoshopprograms,"Translating English texts To Arabic,Teaching E...",Experienced (Non-Manager),"Writing/Editorial, Training/Instructor, Educat..."

In [8]:
# Count duplicates in 'js_id' column
duplicate_count = df1.duplicated(subset=['js_id']).sum()
print("Number of duplicates in 'js_id' column:", duplicate_count)

Number of duplicates in 'js_id' column: 2602532

In [12]:
# Merging the tables on 'js_id'
merged_tables = pd.merge(df1, data, on='js_id', how='inner')
merged_tables.head()

,job_id,Application ID,js_id,Application State,Application Score_x,Application Score_y,text_without_stopwords,job_titles,career_level,js_preference_work_role
0,80546,12895143,ae7c0b81,Shortlisted,55,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
1,2825,13300960,ae7c0b81,Rejected,54,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
2,24626,13029639,ae7c0b81,Ok,62,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
3,32636,16702294,ae7c0b81,Shortlisted,80,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
4,24149,17265467,ae7c0b81,Shortlisted,78,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."

In [13]:
# Filtering the data for 'Shortlisted' or 'Ok' Application State
filtered_data = merged_tables[merged_tables['Application State'].isin(['Shortlisted', 'Ok'])]

filtered_data

,job_id,Application ID,js_id,Application State,Application Score_x,Application Score_y,text_without_stopwords,job_titles,career_level,js_preference_work_role
0,80546,12895143,ae7c0b81,Shortlisted,55,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
2,24626,13029639,ae7c0b81,Ok,62,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
3,32636,16702294,ae7c0b81,Shortlisted,80,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
4,24149,17265467,ae7c0b81,Shortlisted,78,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
5,3307,17265708,ae7c0b81,Shortlisted,72,68.052632,excell word database internetresearch onlinema...,"finance,real estate,sales,retail,brooker,custo...",Experienced (Non-Manager),"Accounting/Finance, Banking, Administration, S..."
...,...,...,...,...,...,...,...,...,...,...
506408,64316,25342682,df7bbbfc,Ok,46,49.500000,autocad dialux etap electricaldistribution sho...,"Electrical Engineer,Electrical Design Engineer...",Experienced (Non-Manager),Engineering - Mechanical/Electrical
506423,15735,25786958,a33fd468,Ok,65,65.000000,interpersonalcommunicationskillscourseauc2016 ...,"Clinical Pathology Specialist,Blood transfusio...",Experienced (Non-Manager),"Quality, Medical/Healthcare"
506426,75000,25855824,9964ae88,Ok,51,51.000000,communication negotiation multitasking dataana...,"Data analysis,Financial analysts, Data analysi...",Entry Level,"Accounting/Finance, Analyst/Research, Banking"
506429,83709,26128359,87ef40dd,Ok,31,31.000000,goodknowledgecoordination excllantcommunicatio...,"Customer service,Accounting,Banker,Bank teller...",Entry Level,"Human Resources, Marketing/PR/Advertising, Acc..."
506430,9402,26128817,79d81893,Ok,57,57.000000,customersupportretention trading finance resea...,"customer support,Finance,Banker,Corporate Bank...",Entry Level,"Analyst/Research, Strategy/Consulting, Busines..."

In [18]:
# Save the filtered data to a CSV file
filtered_data.to_csv('filtered_data.csv', index=False)

In [14]:
# Identify duplicate 'js_id' values
duplicate_js_id = filtered_data[filtered_data.duplicated(subset='js_id', keep=False)]

# The 'duplicate_js_id' DataFrame now contains rows with duplicate 'js_id' values.

# If you want to see the duplicates, you can print the 'duplicate_js_id' DataFrame:
print(duplicate_js_id)

        job_id  Application ID     js_id Application State  \
0        80546        12895143  ae7c0b81       Shortlisted
2        24626        13029639  ae7c0b81                Ok
3        32636        16702294  ae7c0b81       Shortlisted
4        24149        17265467  ae7c0b81       Shortlisted
5         3307        17265708  ae7c0b81       Shortlisted
...        ...             ...       ...               ...
505660   16456        19935104  e0f93147                Ok
505781   19876        17810009  b0d60593       Shortlisted
505782   19876        17810009  b0d60593       Shortlisted
506111   55283        16694911  5222b573                Ok
506112   71124        15170043  5222b573                Ok

        Application Score_x  Application Score_y  \
0                        55            68.052632
2                        62            68.052632
3                        80            68.052632
4                        78            68.052632
5                        72            68.052632
...                     ...                  ...
505660                   51            55.500000
505781                   61            61.000000
505782                   61            61.000000
506111                   57            60.500000
506112                   64            60.500000

                                   text_without_stopwords  \
0       excell word database internetresearch onlinema...
2       excell word database internetresearch onlinema...
3       excell word database internetresearch onlinema...
4       excell word database internetresearch onlinema...
5       excell word database internetresearch onlinema...
...                                                   ...
505660                            microsoftoffice mattlab
505781  dataentry magento2 microsoftexcel e-commerceco...
505782  dataentry magento2 microsoftexcel e-commerceco...
506111                      decisionmaking decisionmaking
506112                      decisionmaking decisionmaking

                                               job_titles  \
0       finance,real estate,sales,retail,brooker,custo...
2       finance,real estate,sales,retail,brooker,custo...
3       finance,real estate,sales,retail,brooker,custo...
4       finance,real estate,sales,retail,brooker,custo...
5       finance,real estate,sales,retail,brooker,custo...
...                                                   ...
505660                      piping engnieer,hvac,drilling
505781  Writing,Data Entry,Managment,Content Creator S...
505782  Writing,Data Entry,Managment,Content Creator S...
506111  System Administrator,Network Administrator,IT,...
506112  System Administrator,Network Administrator,IT,...

                     career_level  \
0       Experienced (Non-Manager)
2       Experienced (Non-Manager)
3       Experienced (Non-Manager)
4       Experienced (Non-Manager)
5       Experienced (Non-Manager)
...                           ...
505660                Entry Level
505781  Experienced (Non-Manager)
505782  Experienced (Non-Manager)
506111                    Manager
506112                    Manager

                                  js_preference_work_role
0       Accounting/Finance, Banking, Administration, S...
2       Accounting/Finance, Banking, Administration, S...
3       Accounting/Finance, Banking, Administration, S...
4       Accounting/Finance, Banking, Administration, S...
5       Accounting/Finance, Banking, Administration, S...
...                                                   ...
505660                Engineering - Mechanical/Electrical
505781  Marketing/PR/Advertising, Sales/Retail, Writin...
505782  Marketing/PR/Advertising, Sales/Retail, Writin...
506111            Administration, IT/Software Development
506112            Administration, IT/Software Development

[127900 rows x 10 columns]

In [15]:
# Check for duplicates in the 'js_id' column
duplicates = filtered_data[filtered_data['js_id'].duplicated(keep=False)]

if not duplicates.empty:
    print("There are duplicated js_id values:")
    print(duplicates)
else:
    print("All js_id values are unique.")

There are duplicated js_id values:
        job_id  Application ID     js_id Application State  \
0        80546        12895143  ae7c0b81       Shortlisted
2        24626        13029639  ae7c0b81                Ok
3        32636        16702294  ae7c0b81       Shortlisted
4        24149        17265467  ae7c0b81       Shortlisted
5         3307        17265708  ae7c0b81       Shortlisted
...        ...             ...       ...               ...
505660   16456        19935104  e0f93147                Ok
505781   19876        17810009  b0d60593       Shortlisted
505782   19876        17810009  b0d60593       Shortlisted
506111   55283        16694911  5222b573                Ok
506112   71124        15170043  5222b573                Ok

        Application Score_x  Application Score_y  \
0                        55            68.052632
2                        62            68.052632
3                        80            68.052632
4                        78            68.052632
5                        72            68.052632
...                     ...                  ...
505660                   51            55.500000
505781                   61            61.000000
505782                   61            61.000000
506111                   57            60.500000
506112                   64            60.500000

                                   text_without_stopwords  \
0       excell word database internetresearch onlinema...
2       excell word database internetresearch onlinema...
3       excell word database internetresearch onlinema...
4       excell word database internetresearch onlinema...
5       excell word database internetresearch onlinema...
...                                                   ...
505660                            microsoftoffice mattlab
505781  dataentry magento2 microsoftexcel e-commerceco...
505782  dataentry magento2 microsoftexcel e-commerceco...
506111                      decisionmaking decisionmaking
506112                      decisionmaking decisionmaking

                                               job_titles  \
0       finance,real estate,sales,retail,brooker,custo...
2       finance,real estate,sales,retail,brooker,custo...
3       finance,real estate,sales,retail,brooker,custo...
4       finance,real estate,sales,retail,brooker,custo...
5       finance,real estate,sales,retail,brooker,custo...
...                                                   ...
505660                      piping engnieer,hvac,drilling
505781  Writing,Data Entry,Managment,Content Creator S...
505782  Writing,Data Entry,Managment,Content Creator S...
506111  System Administrator,Network Administrator,IT,...
506112  System Administrator,Network Administrator,IT,...

                     career_level  \
0       Experienced (Non-Manager)
2       Experienced (Non-Manager)
3       Experienced (Non-Manager)
4       Experienced (Non-Manager)
5       Experienced (Non-Manager)
...                           ...
505660                Entry Level
505781  Experienced (Non-Manager)
505782  Experienced (Non-Manager)
506111                    Manager
506112                    Manager

                                  js_preference_work_role
0       Accounting/Finance, Banking, Administration, S...
2       Accounting/Finance, Banking, Administration, S...
3       Accounting/Finance, Banking, Administration, S...
4       Accounting/Finance, Banking, Administration, S...
5       Accounting/Finance, Banking, Administration, S...
...                                                   ...
505660                Engineering - Mechanical/Electrical
505781  Marketing/PR/Advertising, Sales/Retail, Writin...
505782  Marketing/PR/Advertising, Sales/Retail, Writin...
506111            Administration, IT/Software Development
506112            Administration, IT/Software Development

[127900 rows x 10 columns]

In [16]:
# Check for duplicates in the 'js_id' column
duplicates = filtered_data[filtered_data['js_id'].duplicated(keep=False)]

if not duplicates.empty:
    print("There are duplicated js_id values:")
    print(duplicates)
else:
    print("All js_id values are unique.")

There are duplicated js_id values:
        job_id  Application ID     js_id Application State  \
0        80546        12895143  ae7c0b81       Shortlisted
2        24626        13029639  ae7c0b81                Ok
3        32636        16702294  ae7c0b81       Shortlisted
4        24149        17265467  ae7c0b81       Shortlisted
5         3307        17265708  ae7c0b81       Shortlisted
...        ...             ...       ...               ...
505660   16456        19935104  e0f93147                Ok
505781   19876        17810009  b0d60593       Shortlisted
505782   19876        17810009  b0d60593       Shortlisted
506111   55283        16694911  5222b573                Ok
506112   71124        15170043  5222b573                Ok

        Application Score_x  Application Score_y  \
0                        55            68.052632
2                        62            68.052632
3                        80            68.052632
4                        78            68.052632
5                        72            68.052632
...                     ...                  ...
505660                   51            55.500000
505781                   61            61.000000
505782                   61            61.000000
506111                   57            60.500000
506112                   64            60.500000

                                   text_without_stopwords  \
0       excell word database internetresearch onlinema...
2       excell word database internetresearch onlinema...
3       excell word database internetresearch onlinema...
4       excell word database internetresearch onlinema...
5       excell word database internetresearch onlinema...
...                                                   ...
505660                            microsoftoffice mattlab
505781  dataentry magento2 microsoftexcel e-commerceco...
505782  dataentry magento2 microsoftexcel e-commerceco...
506111                      decisionmaking decisionmaking
506112                      decisionmaking decisionmaking

                                               job_titles  \
0       finance,real estate,sales,retail,brooker,custo...
2       finance,real estate,sales,retail,brooker,custo...
3       finance,real estate,sales,retail,brooker,custo...
4       finance,real estate,sales,retail,brooker,custo...
5       finance,real estate,sales,retail,brooker,custo...
...                                                   ...
505660                      piping engnieer,hvac,drilling
505781  Writing,Data Entry,Managment,Content Creator S...
505782  Writing,Data Entry,Managment,Content Creator S...
506111  System Administrator,Network Administrator,IT,...
506112  System Administrator,Network Administrator,IT,...

                     career_level  \
0       Experienced (Non-Manager)
2       Experienced (Non-Manager)
3       Experienced (Non-Manager)
4       Experienced (Non-Manager)
5       Experienced (Non-Manager)
...                           ...
505660                Entry Level
505781  Experienced (Non-Manager)
505782  Experienced (Non-Manager)
506111                    Manager
506112                    Manager

                                  js_preference_work_role
0       Accounting/Finance, Banking, Administration, S...
2       Accounting/Finance, Banking, Administration, S...
3       Accounting/Finance, Banking, Administration, S...
4       Accounting/Finance, Banking, Administration, S...
5       Accounting/Finance, Banking, Administration, S...
...                                                   ...
505660                Engineering - Mechanical/Electrical
505781  Marketing/PR/Advertising, Sales/Retail, Writin...
505782  Marketing/PR/Advertising, Sales/Retail, Writin...
506111            Administration, IT/Software Development
506112            Administration, IT/Software Development

[127900 rows x 10 columns]

In [17]:
filtered_data.shape

(158466, 10)